//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaOdev.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BorsaOdevEntities : DbContext
    {
        public BorsaOdevEntities()
            : base("name=BorsaOdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblAlici> TblAlicis { get; set; }
        public virtual DbSet<TblKullanici> TblKullanicis { get; set; }
        public virtual DbSet<TblSatici> TblSaticis { get; set; }
        public virtual DbSet<TblUrun> TblUruns { get; set; }
        public virtual DbSet<TblUrunOnay> TblUrunOnays { get; set; }
        public virtual DbSet<TblParaOnay> TblParaOnays { get; set; }
        public virtual DbSet<TblAlimİstek> TblAlimİstek { get; set; }
        public virtual DbSet<TblKasa> TblKasas { get; set; }
    }
}
