//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaOdev.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAlici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAlici()
        {
            this.TblParaOnays = new HashSet<TblParaOnay>();
            this.TblAlimİstek = new HashSet<TblAlimİstek>();
            this.TblAlinanUrunlers = new HashSet<TblAlinanUrunler>();
        }
    
        public int AliciID { get; set; }
        public Nullable<int> AliciPara { get; set; }
        public Nullable<System.DateTime> AlimBaslangic { get; set; }
        public Nullable<System.DateTime> AlimBitis { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Tc { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string kullaniciad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblParaOnay> TblParaOnays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAlimİstek> TblAlimİstek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAlinanUrunler> TblAlinanUrunlers { get; set; }
    }
}
