//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaOdev.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanici
    {
        public int KullaniciID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Tc { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Rol { get; set; }
    }
}
