//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaOdev.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSatici()
        {
            this.TblUrunOnays = new HashSet<TblUrunOnay>();
        }
    
        public int SaticiID { get; set; }
        public Nullable<int> SaticiPara { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Tc { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string kullaniciad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunOnay> TblUrunOnays { get; set; }
    }
}
