//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaOdev.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatilanUrun
    {
        public int SatilanurunID { get; set; }
        public Nullable<int> SaticiID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunMiktar { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
        public Nullable<System.DateTime> UrunSatisBaslangic { get; set; }
        public Nullable<System.DateTime> UrunSatisBitis { get; set; }
    
        public virtual TblSatici TblSatici { get; set; }
    }
}
